### ISSUE TITLE
cloning with draft mode

### ISSUE THREAD

**Issue by dolibit-ut** [ATM-Consulting/dolibarr_module_multiclone#5]
Would it be (technically) possible to duplicate a document in draft mode (PROV) again into a draft mode document?

**Comment by atm-maxime** [comment]
Hi.
Not sure what you mean because this is standard in Dolibarr. Cloning is always available on cards, whatever the status.

**Comment by dolibit-ut** [comment]
Hi,
i meant cloning of a draft when using your module_multiclone.
When i duplicate a draft document with multiclone it is automatically set as confirmed.

**Comment by atm-maxime** [comment]
Yes sorry, it is automatically set as confirmed if you activate this option in setup.

**Comment by dolibit-ut** [comment]
Okay, thanks. This is may be a useful addition for the future.
